### ISSUE TITLE
How to use remarkable-calendar-creator on my remarkable device

### ISSUE THREAD

**Issue by codertjay** [koenvervloesem/remarkable-calendar-creator#2]
Please i am new to shell script so i have my ics url do i just need to follow the steps below to auto update the calendar event because i am scared not to destroy my client device

**Comment by koenvervloesem** [comment]
Just follow the steps in the documentation and all should be right: https://github.com/koenvervloesem/remarkable-calendar-creator#adding-calendar-events

**Comment by codertjay** [comment]
Thanks
